<a href="https://colab.research.google.com/github/zlwym/IAT461_Final_Project/blob/main/final_project_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("listings.csv")

df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,52113003,https://www.airbnb.com/rooms/52113003,20260615212204,2026-06-16,city scrape,King Bed Loft in the Heart of Downtown Boston,"Welcome to our spacious, open-concept loft in ...",NaN,https://a0.muscache.com/pictures/b9802ab5-b0ef...,20828559,...,4.99,4.89,4.84,STR-516048,NaN,1,1,0,0,4.77
1,695542274861997846,https://www.airbnb.com/rooms/695542274861997846,20260615212204,2026-06-16,city scrape,Super 2 Bedroom apt in Beacon Hill Boston,Keep it simple at this peaceful and centrally-...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,373675137,...,5.00,5.00,5.00,NaN,NaN,117,53,64,0,0.11
2,9110708,https://www.airbnb.com/rooms/9110708,20260615212204,2026-07-06,previous scrape,Cozy & sunny apartment BU/Allston,"Cozy 1BR, 1BA apartment in central area of All...",NaN,https://a0.muscache.com/pictures/8b1a6c2f-3135...,32018716,...,NaN,NaN,NaN,NaN,NaN,1,1,0,0,NaN
3,197972,https://www.airbnb.com/rooms/197972,20260615212204,2026-06-16,city scrape,Serene Studio in a Perfect Location,"Our 500 sf 2 room apartment is quiet, private ...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,965697,...,4.97,4.92,4.81,STR-409453,NaN,2,2,0,0,3.33
4,706445990952752456,https://www.airbnb.com/rooms/706445990952752456,20260615212204,2026-06-16,city scrape,Spacious 1br In Boston FIDI | Close to T!,This wonderful 1 bedroom apartment is located ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,382451810,...,4.91,4.91,4.63,STR-489695,NaN,43,43,0,0,4.21

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4378 entries, 0 to 4377
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            4378 non-null   int64
 1   listing_url                                   4378 non-null   object
 2   scrape_id                                     4378 non-null   int64
 3   last_scraped                                  4378 non-null   object
 4   source                                        4378 non-null   object
 5   name                                          4378 non-null   object
 6   description                                   4319 non-null   object
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   4378 non-null   object
 9   host_id                                       4378 non-null   int64
 10  host_url                                      4378 non-null   object
 11  host_profile_id                               4360 non-null   float64
 12  host_profile_url                              4348 non-null   object
 13  host_name                                     4360 non-null   object
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      4360 non-null   float64
 16  hosts_time_as_user_months                     4360 non-null   float64
 17  hosts_time_as_host_years                      4360 non-null   float64
 18  hosts_time_as_host_months                     4360 non-null   float64
 19  host_location                                 3353 non-null   object
 20  host_about                                    2798 non-null   object
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             4360 non-null   object
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              4360 non-null   object
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           4360 non-null   float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          4360 non-null   object
 32  host_identity_verified                        4360 non-null   object
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        4378 non-null   object
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      4378 non-null   float64
 37  longitude                                     4378 non-null   float64
 38  property_type                                 4378 non-null   object
 39  room_type                                     4378 non-null   object
 40  accommodates                                  4378 non-null   int64
 41  bathrooms                                     3348 non-null   float64
 42  bathrooms_text                                4343 non-null   object
 43  bedrooms                                      3117 non-null   float64
 44  beds                                          3449 non-null   float64
 45  amenities                                     4378 non-null   object
 46  price                                         3693 non-null   object
 47  price_quote_checkin_date                      3922 non-null   object
 48  price_quote_checkout_date                     3922 non-null   object
 49  price_quote_total_price                       3693 non-null   float64
 50  price_quote_price_per_night                   3693 non-null   float64
 51  price_quote_raw                               3922 non-null   object
 52  minimum_nights                                4378 non-null   int64
 53  maximum_nights                                4378 non-null   int64
 54  minimum_minimum_nights                        4378 non-null   int64
 55  maximum_minimum_nights                        4378 non-null   int64
 56  minimum_maximum_nights                        4378 non-null   int64
 57  maximum_maximum_nights                        4378 non-null   int64
 58  minimum_nights_avg_ntm                        4378 non-null   float64
 59  maximum_nights_avg_ntm                        4378 non-null   float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              4345 non-null   object
 62  availability_30                               4378 non-null   int64
 63  availability_60                               4378 non-null   int64
 64  availability_90                               4378 non-null   int64
 65  availability_365                              4378 non-null   int64
 66  calendar_last_scraped                         4378 non-null   object
 67  number_of_reviews                             4378 non-null   int64
 68  number_of_reviews_ltm                         4378 non-null   int64
 69  number_of_reviews_l30d                        4378 non-null   int64
 70  availability_eoy                              4378 non-null   int64
 71  number_of_reviews_ly                          4378 non-null   int64
 72  estimated_occupancy_l365d                     4378 non-null   int64
 73  estimated_revenue_l365d                       3693 non-null   float64
 74  first_review                                  3477 non-null   object
 75  last_review                                   3477 non-null   object
 76  review_scores_rating                          3477 non-null   float64
 77  review_scores_accuracy                        3476 non-null   float64
 78  review_scores_cleanliness                     3477 non-null   float64
 79  review_scores_checkin                         3476 non-null   float64
 80  review_scores_communication                   3477 non-null   float64
 81  review_scores_location                        3476 non-null   float64
 82  review_scores_value                           3476 non-null   float64
 83  license                                       3150 non-null   object
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                4378 non-null   int64
 86  calculated_host_listings_count_entire_homes   4378 non-null   int64
 87  calculated_host_listings_count_private_rooms  4378 non-null   int64
 88  calculated_host_listings_count_shared_rooms   4378 non-null   int64
 89  reviews_per_month                             3477 non-null   float64
dtypes: float64(37), int64(24), object(29)
memory usage: 3.0+ MB

In [ ]:
df.describe()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,4.378000e+03,4.378000e+03,0.0,4.378000e+03,4.360000e+03,0.0,4360.000000,4360.000000,4360.000000,4360.000000,...,3476.000000,3477.000000,3476.000000,3476.000000,0.0,4378.000000,4378.000000,4378.000000,4378.000000,3477.000000
mean,8.176489e+17,2.026062e+13,NaN,1.266426e+16,1.473194e+18,NaN,7.994725,5.775229,6.606881,5.677064,...,4.856392,4.848225,4.765570,4.625046,NaN,30.073550,24.379625,4.978986,0.009822,1.727291
std,6.442407e+17,2.375271e+00,NaN,1.453351e+17,3.387821e+16,NaN,4.064542,3.547266,4.179232,3.409409,...,0.317106,0.329988,0.327309,0.419755,NaN,52.975297,51.752829,12.400281,0.098629,1.882912
min,3.781000e+03,2.026062e+13,NaN,4.804000e+03,1.462506e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,4.553112e+07,2.026062e+13,NaN,2.234822e+07,1.462889e+18,NaN,5.000000,3.000000,3.000000,3.000000,...,4.840000,4.840000,4.680000,4.520000,NaN,2.000000,1.000000,0.000000,0.000000,0.280000
50%,9.659016e+17,2.026062e+13,NaN,1.074344e+08,1.465718e+18,NaN,9.000000,6.000000,7.000000,6.000000,...,4.940000,4.940000,4.870000,4.720000,NaN,7.000000,3.000000,0.000000,0.000000,1.070000
75%,1.415532e+18,2.026062e+13,NaN,3.824518e+08,1.469716e+18,NaN,11.000000,9.000000,10.000000,9.000000,...,5.000000,5.000000,4.990000,4.860000,NaN,34.000000,19.000000,3.000000,0.000000,2.650000
max,1.706947e+18,2.026062e+13,NaN,1.694941e+18,1.706947e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,5.000000,NaN,227.000000,227.000000,64.000000,1.000000,24.160000

In [ ]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [ ]:
df.isnull().sum()

id                                                0
listing_url                                       0
scrape_id                                         0
last_scraped                                      0
source                                            0
                                               ...
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
calculated_host_listings_count_private_rooms      0
calculated_host_listings_count_shared_rooms       0
reviews_per_month                               901
Length: 90, dtype: int64